name: Update FRED CSVs

on:
  workflow_dispatch:
  schedule:
    - cron: "15 18 * * *" # daily 18:15 UTC

permissions:
  contents: write

concurrency:
  group: fred-csv
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch & append FRED data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: node scripts/fetch-fred-csv.mjs

      - name: Commit changes
        run: |
          echo "Git status (porcelain):"
          git status --porcelain

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "chore: update FRED CSVs"
          git push