/* ============================================================
   Liberal Markets — app.js
   Full client logic
   - Tape loads from static tape.json (GitHub Actions)
   - Restores: filters, sorting, pinning, signals rail, export pins,
     density toggle, and Cmd/Ctrl+K quick search modal.
   ============================================================ */

/* ---------------- Utilities ---------------- */

/**
 * Escape text for safe HTML insertion.
 * @param {string} s
 * @returns {string}
 */
function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  }[c]));
}

/**
 * Clamp a number.
 * @param {number} n
 * @param {number} min
 * @param {number} max
 * @returns {number}
 */
function clamp(n, min, max) {
  return Math.min(max, Math.max(min, n));
}

/**
 * Format a percent change.
 * @param {number} n
 * @returns {string}
 */
function pct(n) {
  const sign = n >= 0 ? "+" : "";
  return `${sign}${n.toFixed(2)}%`;
}

/**
 * Format a date like "Jan 4".
 * @param {string} iso
 * @returns {string}
 */
function fmtDate(iso) {
  const d = new Date(iso);
  return d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

/**
 * Set innerHTML.
 * @param {HTMLElement} el
 * @param {string} html
 */
function setHTML(el, html) {
  el.innerHTML = html;
}

/**
 * Render a tiny wire chevron indicating up/down.
 * @param {boolean} up
 * @returns {string}
 */
function chevronSVG(up) {
  const rot = up ? "rotate(0)" : "rotate(180deg)";
  return `
    <svg viewBox="0 0 24 24" class="chev" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="transform:${rot}">
      <path d="M6 14l6-6 6 6"></path>
    </svg>
  `;
}


/**
 * Persist pins to localStorage.
 * @param {Set<string>} pins
 */
function savePins(pins) {
  localStorage.setItem("lw_pins", JSON.stringify([...pins]));
}

/**
 * Load pins from localStorage.
 * @returns {Set<string>}
 */
function loadPins() {
  try {
    const raw = localStorage.getItem("lw_pins");
    if (!raw) return new Set();
    const arr = JSON.parse(raw);
    return new Set(Array.isArray(arr) ? arr : []);
  } catch {
    return new Set();
  }
}

/**
 * Persist pinned notes to localStorage.
 * Notes are stored as an array of objects.
 * @param {Array<{id:string,title:string,excerpt:string,url:string,ts:number}>} notes
 */
function saveNotePins(notes) {
  localStorage.setItem("lw_note_pins", JSON.stringify(notes));
}

/**
 * Load pinned notes from localStorage.
 * @returns {Array<{id:string,title:string,excerpt:string,url:string,ts:number}>}
 */
function loadNotePins() {
  try {
    const raw = localStorage.getItem("lw_note_pins");
    if (!raw) return [];
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

/* ---------------- Config ---------------- */

const WATCH = [
  { sym: "10yusy.b", name: "US 10Y Yield" },
  { sym: "usdeur", name: "USD/EUR" },
  { sym: "cb.f", name: "Brent" },
  { sym: "^spx", name: "S&P 500" },
  { sym: "xauusd", name: "Gold" },
  { sym: "asts.us", name: "ASTS" },
];

/**
 * @typedef {Object} Post
 * @property {string} id
 * @property {string} title
 * @property {string} desc
 * @property {string[]} tags
 * @property {string} category
 * @property {string} dateISO
 * @property {number} minutes
 * @property {number} signal
 */

/** @type {Post[]} */
let POSTS = [];

async function loadPosts() {
  const day = new Date().toISOString().slice(0, 10);
  const res = await fetch(`data/posts.json?v=${day}`, { cache: "no-store" });
  if (!res.ok) throw new Error("Failed to load posts.json");
  const json = await res.json();
  POSTS = Array.isArray(json.posts) ? json.posts : [];
}

/* ---------------- Tape (static JSON) ---------------- */

/**
 * Load tape.json generated by GitHub Actions.
 * Cache-bust daily so visitors get the latest close after the daily update.
 * @returns {Promise<Array<any>>}
 */
async function loadTapeFromJson() {
  const day = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const res = await fetch(`/tape.json?v=${day}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Failed to load tape.json (${res.status})`);
  const data = await res.json();
  return Array.isArray(data.items) ? data.items : [];
}



/**
 * Render the tape panel from tape.json.
 */
async function renderTape() {
  const list = document.getElementById("tape");
  if (!list) return;

  // placeholder
  setHTML(list, WATCH.map(w => `
    <li class="tick">
      <div class="tickLeft">
        <span class="badge">${esc(w.sym.toUpperCase())}</span>
        <span class="tickName">${esc(w.name)}</span>
      </div>
      <div class="tickRight">
        <div>—</div>
        <div class="delta"><span>loading</span></div>
      </div>
    </li>
  `).join(""));

  let items;
  try {
    items = await loadTapeFromJson();
  } catch {
    setHTML(list, `<li class="muted">Tape unavailable</li>`);
    return;
  }

  const bySym = new Map(items.map(i => [i.sym, i]));
  const rows = WATCH.map(w => {
    const d = bySym.get(w.sym);
    return d && d.ok ? d : { ...w, ok: false };
  });


  const dateEl = document.getElementById("lastSync");
  const latestDate = rows.filter(r => r.ok).map(r => r.date).sort().pop();
  if (dateEl) dateEl.textContent = latestDate ? `Close: ${latestDate}` : "Close: —";

  setHTML(list, rows.map(d => {
    if (!d.ok || !Number.isFinite(Number(d.close))) {
      return `
        <li class="tick">
          <div class="tickLeft">
            <span class="badge">${esc(d.sym.toUpperCase())}</span>
            <span class="tickName">${esc(d.name)}</span>
          </div>
          <div class="tickRight">
            <div>n/a</div>
            <div class="delta"><span>no data</span></div>
          </div>
        </li>
      `;
    }

    const deltaPct = Number(d.deltaPct);
    const up = Number.isFinite(deltaPct) ? deltaPct >= 0 : true;
    const deltaClass = up ? "deltaUp" : "deltaDown";

    return `
      <li class="tick">
        <div class="tickLeft">
          <span class="badge">${esc(String(d.sym).toUpperCase())}</span>
          <span class="tickName">${esc(String(d.name))}</span>
        </div>
        <div class="tickRight">
          <div>${Number(d.close).toFixed(2)}</div>
          <div class="delta ${deltaClass}">
            ${Number.isFinite(deltaPct) ? chevronSVG(up) : ""}
            <span>${Number.isFinite(deltaPct) ? pct(deltaPct) : "—"}</span>
          </div>
        </div>
      </li>
    `;
  }).join(""));
}

/* ---------------- Posts / Filters / UI ---------------- */

const state = { filter: "all", q: "", sort: "new" };
const pinSet = loadPins();
let notePins = loadNotePins();

/**
 * Apply filter + search + sort.
 * @param {{filter:string, q:string, sort:string}} s
 * @returns {Post[]}
 */
function selectPosts(s) {
  const query = s.q.trim().toLowerCase();

  let items = POSTS.slice();

  if (s.filter !== "all") {
    items = items.filter(p => p.category === s.filter);
  }

  if (query) {
    items = items.filter(p => {
      const blob = `${p.title} ${p.desc} ${p.tags.join(" ")} ${p.category}`.toLowerCase();
      return blob.includes(query);
    });
  }

  if (s.sort === "new") {
    items.sort((a, b) => new Date(b.dateISO).getTime() - new Date(a.dateISO).getTime());
  } else if (s.sort === "signal") {
    items.sort((a, b) => b.signal - a.signal);
  } else if (s.sort === "read") {
    items.sort((a, b) => a.minutes - b.minutes);
  }

  return items;
}

/**
 * Render posts.
 * @param {Post[]} posts
 * @param {Set<string>} pins
 */
function renderPosts(posts, pins) {
  const postList = document.getElementById("postList");
  const pill = document.getElementById("resultPill");
  if (!postList) return;

  if (pill) pill.textContent = `${posts.length} shown`;

  setHTML(postList, posts.map(p => {
    const scoreW = clamp(p.signal, 0, 100);
    const isPinned = pins.has(p.id);
    const pinLabel = isPinned ? "Pinned" : "Pin";
    const pinIcon = `
      <svg viewBox="0 0 640 640" class="icon" fill="currentColor" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><!--!Font Awesome Free v7.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.--><path d="M160 96C160 78.3 174.3 64 192 64L448 64C465.7 64 480 78.3 480 96C480 113.7 465.7 128 448 128L418.5 128L428.8 262.1C465.9 283.3 494.6 318.5 507 361.8L510.8 375.2C513.6 384.9 511.6 395.2 505.6 403.3C499.6 411.4 490 416 480 416L160 416C150 416 140.5 411.3 134.5 403.3C128.5 395.3 126.5 384.9 129.3 375.2L133 361.8C145.4 318.5 174 283.3 211.2 262.1L221.5 128L192 128C174.3 128 160 113.7 160 96zM288 464L352 464L352 576C352 593.7 337.7 608 320 608C302.3 608 288 593.7 288 576L288 464z"/></svg>
    `;

    return `
      <article class="post" data-id="${esc(p.id)}">
        <div class="postInner">
          <div class="postTop">
            <div class="tagRow">
              ${p.tags.slice(0, 3).map(t => `<span class="tag">${esc(t)}</span>`).join(" ")}
            </div>
            <div class="score" title="Signal score">
              <span>${p.signal}</span>
              <span class="scoreBar" aria-hidden="true">
                <span class="scoreFill" style="width:${scoreW}%"></span>
              </span>
            </div>
          </div>

          <h3 class="postTitle">
            <a href="#" data-open="${esc(p.id)}">${esc(p.title)}</a>
          </h3>

          <p class="postDesc">${esc(p.desc)}</p>

          <div class="postFoot">
            <div class="meta">
              <span>${fmtDate(p.dateISO)}</span>
              <span class="dot" aria-hidden="true"></span>
              <span>${p.minutes} min</span>
              <span class="dot" aria-hidden="true"></span>
              <span>${esc(p.category)}</span>
            </div>
            <button class="pinIt" type="button" data-pin="${esc(p.id)}" aria-pressed="${isPinned}">
              ${pinIcon}
              <span>${pinLabel}</span>
            </button>
          </div>
        </div>
      </article>
    `;
  }).join(""));
}

/**
 * Render signals and pins in the left rail.
 * @param {Post[]} currentPosts
 * @param {Set<string>} pins
 */
function renderRail(currentPosts, pins) {
  const signals = document.getElementById("signals");
  const pinsEl = document.getElementById("pins");
  if (!signals || !pinsEl) return;

  const topSignals = [...currentPosts].sort((a, b) => b.signal - a.signal).slice(0, 4);

  const icon = `
    <svg viewBox="0 0 24 24" class="icon" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
      <path d="M4 18V6"></path>
      <path d="M4 18h16"></path>
      <path d="M7 16l3-3 3 2 5-6"></path>
      <path d="M17 9h2v2"></path>
    </svg>
  `;

  const unpinIcon = `
      <svg viewBox="0 0 640 640" class="icon" fill="currentColor" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><!--!Font Awesome Free v7.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.--><path d="M73 39.1C63.6 29.7 48.4 29.7 39.1 39.1C29.8 48.5 29.7 63.7 39 73.1L567 601.1C576.4 610.5 591.6 610.5 600.9 601.1C610.2 591.7 610.3 576.5 600.9 567.2L449.8 416L480 416C490 416 499.5 411.3 505.5 403.3C511.5 395.3 513.5 384.9 510.7 375.2L507 361.8C494.6 318.5 466 283.3 428.8 262.1L418.5 128L448 128C465.7 128 480 113.7 480 96C480 78.3 465.7 64 448 64L192 64C184.6 64 177.9 66.5 172.5 70.6L222.1 120.3L217.3 183.4L73 39.1zM314.2 416L181.7 283.6C159 304.1 141.9 331 133 361.9L129.2 375.3C126.4 385 128.4 395.3 134.4 403.4C140.4 411.5 150 416 160 416L314.2 416zM288 576C288 593.7 302.3 608 320 608C337.7 608 352 593.7 352 576L352 464L288 464L288 576z"/></svg>
    `;  
  const openIcon = `
      <svg viewBox="0 0 640 640" class="icon" fill="currentColor" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><!--!Font Awesome Free v7.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.--><path d="M320 205.3L320 514.6L320.5 514.4C375.1 491.7 433.7 480 492.8 480L512 480L512 160L492.8 160C450.6 160 408.7 168.4 369.7 184.6C352.9 191.6 336.3 198.5 320 205.3zM294.9 125.5L320 136L345.1 125.5C391.9 106 442.1 96 492.8 96L528 96C554.5 96 576 117.5 576 144L576 496C576 522.5 554.5 544 528 544L492.8 544C442.1 544 391.9 554 345.1 573.5L332.3 578.8C324.4 582.1 315.6 582.1 307.7 578.8L294.9 573.5C248.1 554 197.9 544 147.2 544L112 544C85.5 544 64 522.5 64 496L64 144C64 117.5 85.5 96 112 96L147.2 96C197.9 96 248.1 106 294.9 125.5z"/></svg>
    `;

  setHTML(signals, topSignals.map(p => `
    <div class="signal">
      <div class="signalLeft">
        <div class="sigIcon" aria-hidden="true">${icon}</div>
        <div class="sigName" title="${esc(p.title)}">${esc(p.title)}</div>
      </div>
      <div class="sigVal">${p.signal}</div>
    </div>
  `).join(""));

  const pinnedPosts = POSTS.filter(p => pins.has(p.id)).slice(0, 6);
  const pinnedNotes = (notePins || []).slice(0, 6);

  if (pinnedPosts.length === 0 && pinnedNotes.length === 0) {
    setHTML(pinsEl, `<div class="muted">Pin a post or note to keep it here.</div>`);
    return;
  }

  const notesHTML = pinnedNotes.map(n => `
    <div class="pin">
      <div class="pinTitle" title="${esc(n.excerpt || n.title || "Note")}">
        ${esc(n.title || "Note")}
      </div>
      <div style="display:flex; gap:8px; align-items:center;">
        <a class="pinBtn pinBtnIcon" href="${esc(n.url)}" style="text-decoration:none;">${openIcon}</a>
        <button
        class="pinBtn pinBtnIcon"
        type="button"
        data-unpin-note="${esc(n.id)}"
        aria-label="Unpin note"
        title="Unpin note"
        >
          ${unpinIcon}
        </button>
      </div>
    </div>
  `).join("");

  const postsHTML = pinnedPosts.map(p => `
    <div class="pin">
      <div class="pinTitle" title="${esc(p.title)}">${esc(p.title)}</div>
        <button
        class="pinBtn pinBtnIcon"
        type="button"
        data-unpin-note="${esc(p.id)}"
        aria-label="Unpin note"
        title="Unpin note"
        >
          ${unpinIcon}
        </button>
    </div>
  `).join("");

  setHTML(pinsEl, notesHTML + postsHTML);
}

/**
 * Lightweight "reader" placeholder.
 * @param {Post} post
 */
function openPost(post) {
  const lines = [
    post.title,
    "",
    `Category: ${post.category}`,
    `Date: ${post.dateISO}`,
    `Reading: ${post.minutes} min`,
    `Signal: ${post.signal}`,
    "",
    post.desc,
    "",
    "This is a single-page demo. Wire it to real routes when you're done being mortal.",
  ];
  alert(lines.join("\n"));
}

/**
 * Render the modal quick search list.
 * @param {Post[]} posts
 */
function renderModalList(posts) {
  const modalList = document.getElementById("modalList");
  if (!modalList) return;

  setHTML(modalList, posts.map(p => `
    <div class="modalItem" role="button" tabindex="0" data-open="${esc(p.id)}">
      <div class="modalItemTitle">${esc(p.title)}</div>
      <div class="modalItemMeta">${esc(p.category)} • ${p.minutes}m</div>
    </div>
  `).join(""));
}


/**
 * Load a CSV and return the latest (last) non-empty numeric row.
 * Assumes header: date,value and date is YYYY-MM-DD.
 * @param {string} csvPath
 * @returns {Promise<{date:string, value:number} | null>}
 */
async function loadLatestFromCsv(csvPath) {
  const day = new Date().toISOString().slice(0, 10);
  const res = await fetch(`${csvPath}?v=${day}`, { cache: "no-store" });
  if (!res.ok) return null;

  const text = await res.text();
  const lines = text.trim().split("\n").filter(Boolean);
  if (lines.length <= 1) return null;

  // Walk backwards to find the latest valid numeric value
  for (let i = lines.length - 1; i >= 1; i--) {
    const [dateRaw, valRaw] = lines[i].split(",");
    const date = (dateRaw ?? "").trim();
    const value = Number((valRaw ?? "").trim());
    if (date && Number.isFinite(value)) return { date, value };
  }
  return null;
}

/**
 * Render economic indicators in the hero stats from /data CSVs.
 */
async function renderHeroIndicators() {
  const cpiVal = document.getElementById("cpiVal");
  const unrateVal = document.getElementById("unrateVal");
  const gdpVal = document.getElementById("gdpVal");
  const mincVal = document.getElementById("mincVal");
  const mhouVal = document.getElementById("mhouVal");
  const ratioVal = document.getElementById("ratioVal");

  const cpiLabel = document.getElementById("cpiLabel");
  const unrateLabel = document.getElementById("unrateLabel");
  const gdpLabel = document.getElementById("gdpLabel");
  const mincLabel = document.getElementById("mincLabel");
  const mhouLabel = document.getElementById("mhouLabel");
  const ratioLabel = document.getElementById("ratioLabel");

  const [cpi, unrate, gdp, income, house, ratio] = await Promise.all([
    loadLatestFromCsv("/data/CPIAUCSL.csv"),
    loadLatestFromCsv("/data/UNRATE.csv"),
    loadLatestFromCsv("/data/GDPC1.csv"),
    loadLatestFromCsv("/data/MEHOINUSA646N.csv"),
    loadLatestFromCsv("/data/MSPUS.csv"),
    loadLatestFromCsv("/data/HOUSE_TO_INCOME_RATIO.csv"),
  ]);

  if (cpiVal) cpiVal.textContent = cpi ? cpi.value.toFixed(3) : "—";
  if (unrateVal) unrateVal.textContent = unrate ? `${unrate.value.toFixed(1)}%` : "—";
  if (gdpVal) gdpVal.textContent = gdp ? gdp.value.toFixed(0) : "—";
  if (mincVal) mincVal.textContent = income ? income.value.toFixed(0) : "—";  
  if (mhouVal) mhouVal.textContent = house ? house.value.toFixed(0) : "—";
  if (ratioVal) ratioVal.textContent = ratio ? ratio.value.toFixed(0) : "—";
  // Optional: keep it minimalist by putting dates in the label

}






/* ---------------- Init ---------------- */

(async function init() {
  // footer + header stats
  const yearEl = document.getElementById("year");
  if (yearEl) yearEl.textContent = String(new Date().getFullYear());

  await loadPosts();

  const initial = selectPosts(state);
  renderPosts(initial, pinSet);
  renderRail(initial, pinSet);


  // initial renders
  renderTape();
  renderHeroIndicators();

  // Keep note pins in sync when another page updates localStorage.
  window.addEventListener("storage", (e) => {
    if (e.key === "lw_note_pins") {
      notePins = loadNotePins();
      const posts = selectPosts(state);
      renderRail(posts, pinSet);
    }
  });

  // Also refresh when returning to the tab/page (covers back-navigation cases).
  document.addEventListener("visibilitychange", () => {
    if (document.visibilityState !== "visible") return;
    notePins = loadNotePins();
    const posts = selectPosts(state);
    renderRail(posts, pinSet);
  });


  // Filter chips
  document.querySelectorAll(".chip").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".chip").forEach(b => b.classList.remove("is-active"));
      btn.classList.add("is-active");
      document.querySelectorAll(".chip").forEach(b => b.setAttribute("aria-pressed", String(b === btn)));

      state.filter = btn.getAttribute("data-filter") || "all";
      const posts = selectPosts(state);
      renderPosts(posts, pinSet);
      renderRail(posts, pinSet);
    });
  });

  // Sort buttons
  document.querySelectorAll(".sortBtn").forEach(btn => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".sortBtn").forEach(b => b.classList.remove("is-active"));
      btn.classList.add("is-active");
      document.querySelectorAll(".sortBtn").forEach(b => b.setAttribute("aria-pressed", String(b === btn)));

      state.sort = btn.getAttribute("data-sort") || "new";
      const posts = selectPosts(state);
      renderPosts(posts, pinSet);
      renderRail(posts, pinSet);
    });
  });

  // Search input
  const q = document.getElementById("q");
  if (q) {
    q.addEventListener("input", () => {
      state.q = q.value;
      const posts = selectPosts(state);
      renderPosts(posts, pinSet);
      renderRail(posts, pinSet);
    });
  }

  // Density toggle
  const densityBtn = document.getElementById("toggleDensity");
  if (densityBtn) {
    densityBtn.addEventListener("click", () => {
      const compact = document.body.classList.toggle("compact");
      densityBtn.setAttribute("aria-pressed", String(compact));
    });
  }

  // Post interactions + pin/unpin (event delegation)
  document.addEventListener("click", (e) => {
    const t = /** @type {HTMLElement} */ (e.target);

    const openId = t.closest("[data-open]")?.getAttribute("data-open");
    if (openId) {
      const post = POSTS.find(p => p.id === openId);
      if (post) openPost(post);
      return;
    }

    const pinId = t.closest("[data-pin]")?.getAttribute("data-pin");
    if (pinId) {
      if (pinSet.has(pinId)) pinSet.delete(pinId);
      else pinSet.add(pinId);

      savePins(pinSet);

      const posts = selectPosts(state);
      renderPosts(posts, pinSet);
      renderRail(posts, pinSet);
      return;
    }

    const unpinId = t.closest("[data-unpin]")?.getAttribute("data-unpin");
    if (unpinId) {
      pinSet.delete(unpinId);
      savePins(pinSet);

      const posts = selectPosts(state);
      renderPosts(posts, pinSet);
      renderRail(posts, pinSet);
      return;
    }

    const unpinNoteId = t.closest("[data-unpin-note]")?.getAttribute("data-unpin-note");
    if (unpinNoteId) {
      notePins = (notePins || []).filter(n => n.id !== unpinNoteId);
      saveNotePins(notePins);

      const posts = selectPosts(state);
      renderPosts(posts, pinSet);
      renderRail(posts, pinSet);
      return;
    }

    // Export pins
    const exportBtn = t.closest("#exportBtn");
    if (exportBtn) {
      e.preventDefault();
      const pinnedPosts = POSTS.filter(p => pinSet.has(p.id)).map(p => ({
        type: "post",
        id: p.id,
        title: p.title,
        date: p.dateISO,
        category: p.category,
        tags: p.tags,
      }));

      const pinnedNotes = (notePins || []).map(n => ({
        type: "note",
        id: n.id,
        title: n.title,
        excerpt: n.excerpt,
        url: n.url,
        ts: n.ts,
      }));

      const blob = new Blob([
        JSON.stringify(
          { exportedAt: new Date().toISOString(), pinnedPosts, pinnedNotes },
          null,
          2
        )
      ], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "liberal-markets-pins.json";
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    }
  });

  // Modal quick search: ⌘K / Ctrl+K
  const modal = /** @type {HTMLDialogElement|null} */ (document.getElementById("modal"));
  const modalQ = /** @type {HTMLInputElement|null} */ (document.getElementById("modalQ"));

  /**
   * @param {string} query
   */
  function updateModal(query) {
    const tmp = { ...state, q: query };
    const posts = selectPosts(tmp);
    renderModalList(posts);
  }

  document.addEventListener("keydown", (e) => {
    if (!modal || !modalQ) return;

    const isMac = navigator.platform.toLowerCase().includes("mac");
    const cmd = isMac ? e.metaKey : e.ctrlKey;

    if (cmd && e.key.toLowerCase() === "k") {
      e.preventDefault();
      modal.showModal();
      modalQ.value = state.q || "";
      updateModal(modalQ.value);
      modalQ.focus();
    }

    if (e.key === "Escape" && modal.open) modal.close();
  });

  if (modalQ) {
    modalQ.addEventListener("input", () => updateModal(modalQ.value));
  }

  const modalList = document.getElementById("modalList");
  if (modalList) {
    modalList.addEventListener("click", (e) => {
      if (!modal) return;
      const t = /** @type {HTMLElement} */ (e.target);
      const openId = t.closest("[data-open]")?.getAttribute("data-open");
      if (!openId) return;
      const post = POSTS.find(p => p.id === openId);
      if (post) {
        modal.close();
        openPost(post);
      }
    });

    modalList.addEventListener("keydown", (e) => {
      if (!modal) return;
      const ke = /** @type {KeyboardEvent} */ (e);
      if (ke.key !== "Enter") return;
      const t = /** @type {HTMLElement} */ (ke.target);
      const openId = t.closest("[data-open]")?.getAttribute("data-open");
      if (!openId) return;
      const post = POSTS.find(p => p.id === openId);
      if (post) {
        modal.close();
        openPost(post);
      }
    });
  }
})();
