import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { loadTradingPostAsset, createTradingPost, animateTradingPost } from '../trade-winds-market-models.mjs';
const bytes = readFileSync(new URL('../assets/trade-winds/models/clean-character-harbor.glb', import.meta.url));
const gltf = JSON.parse(bytes.subarray(20, 20 + bytes.readUInt32LE(12)));
test('harbor exports its camera and all requested animation subjects', () => {
  assert.equal(bytes.toString('ascii',0,4),'glTF');
  assert.ok(bytes.length < 60*1024*1024);
  assert.equal(gltf.images, undefined);
  assert.equal(gltf.animations.length, 1);
  assert.equal(gltf.cameras.length, 1);
  const animated = new Set(gltf.animations.flatMap(a => a.channels.map(c => gltf.nodes[c.target.node].name)));
  for (const name of ['merchant_head','drunkard_body','drunkard_arm_left','dockhand_a_head','dockhand_b_head','dockhand_c_head','rope_swing_0','rope_swing_1','lantern_swing','ship_grand_merchant']) assert.ok(animated.has(name), name);
  const blink = gltf.animations[0].channels.filter(c=>c.target.path==='weights');
  assert.ok(blink.some(c=>gltf.nodes[c.target.node].name.startsWith('08 Merchant::Head')));
  assert.equal(Math.max(...gltf.animations[0].samplers.map(s=>gltf.accessors[s.input].max[0])),20);
  assert.ok(gltf.nodes.some(n=>n.camera===0 && n.extras.authoredHarbor));
});
test('packed asset loads, animates independently, and respects reduced motion', async t => {
  let requests=0;
  t.mock.method(globalThis,'fetch',async request=>{assert.match(request.url,/clean-character-harbor\.glb$/);requests++;return new Response(bytes);});
  const previous=globalThis.ProgressEvent;
  globalThis.ProgressEvent=class extends Event {constructor(type,init){super(type);Object.assign(this,init);}};
  t.after(()=>{if(previous)globalThis.ProgressEvent=previous;else delete globalThis.ProgressEvent;});
  await Promise.all([loadTradingPostAsset(),loadTradingPostAsset()]);
  assert.equal(requests,1);
  const a=createTradingPost(),b=createTradingPost();
  assert.notEqual(a.userData.mixer,b.userData.mixer);
  const arm=a.getObjectByName('drunkard_arm_left');
  animateTradingPost(a,0);const rest=arm.quaternion.clone();
  animateTradingPost(a,5);assert.ok(rest.angleTo(arm.quaternion)>.5,'tankard reaches sip pose');
  assert.ok(rest.angleTo(b.getObjectByName('drunkard_arm_left').quaternion)<.001);
  const eyes=[];
  a.userData.merchantHead.traverse(o=>{if(o.morphTargetInfluences) eyes.push(o);});
  assert.equal(eyes.length,2);
  animateTradingPost(a,55/24);
  for(const eye of eyes) assert.ok(eye.morphTargetInfluences[0]>.95,'merchant closes both eyes');
  animateTradingPost(a,3);
  for(const eye of eyes) assert.ok(eye.morphTargetInfluences[0]<.001,'merchant reopens both eyes');
  const ship=a.getObjectByName('ship_grand_merchant');
  animateTradingPost(a,2);const bob=ship.position.clone();
  animateTradingPost(a,6);assert.ok(bob.distanceTo(ship.position)>.05);
  a.userData.lookYaw=.18;
  animateTradingPost(a,10,0,true);const still=arm.quaternion.clone();const head=a.userData.merchantHead.quaternion.clone();
  animateTradingPost(a,30,1,true);assert.ok(still.angleTo(arm.quaternion)<.001);assert.ok(head.angleTo(a.userData.merchantHead.quaternion)<.001);
  assert.ok(a.userData.lights.length>=3);
  for(const {light,power} of a.userData.lights)assert.equal(light.intensity,power);
  assert.equal(a.userData.authoredHarbor,true);
  animateTradingPost(a,0);const first=arm.quaternion.clone();
  animateTradingPost(a,20);assert.ok(first.angleTo(arm.quaternion)<.001,'twenty-second loop closes');
});
